src/mobx/stores/LockedDepositsStore.ts

fix: locked store crashes app on networks with no locker

---

src/components-v2/VaultApyInformation/index.tsx
src/components-v2/VaultDeprecationWarning/index.tsx
src/components-v2/landing/VaultListItem.tsx
src/components-v2/landing/VaultListItemMobile.tsx
src/components-v2/navbar/NavbarTabs.tsx
src/components-v2/vault-detail/TopContent.tsx
src/config/routes.tsx

fix: replace sett naming in url route and fix inactive tab in nested params

---

src/components-v2/NetworkURLManager/index.tsx
src/components-v2/VaultApyInformation/index.tsx
src/components-v2/common/NetworkWidget.tsx
src/components-v2/network-selector/NetworkOption.tsx
src/config/constants.ts
src/config/routes.tsx
src/hooks/usePrevious.ts
src/index.tsx
src/mobx/stores/NetworkStore.ts
src/mobx/stores/OnboardStore.ts
src/mobx/stores/VaultStore.ts

feat: add url params support

---

src/components-v2/network-selector/GasOptions.tsx
src/components-v2/network-selector/NetworkOption.tsx
src/mobx/stores/NetworkStore.ts
src/mobx/stores/contractsStore.ts
src/mobx/stores/honeyPotStore.ts
src/mobx/stores/ibBTCStore.ts
src/mobx/stores/uiStore.ts
src/tests/NetworkGasWidget.test.tsx
src/tests/__snapshots__/NetworkGasWidget.test.tsx.snap

feat: Network selection > Show gas  + gas price usage fix

---

src/config/ui/dark.tsx
src/stories/Dialog.stories.tsx

feat(ui-library): add dialogs style config

---

src/config/ui/dark.tsx
src/stories/Switch.stories.tsx
src/stories/SwitchWithLabel.stories.tsx

feat(ui-library): add switches theme config

---

src/config/ui/dark.tsx
src/stories/Button.stories.tsx

feat(ui-library): adjust button sizes

---

src/components-v2/VaultSearchControls/VaultFiltersDialog.tsx
src/components-v2/common/PercentageSelector.tsx
src/components-v2/common/dialogs/NoRewardsDialog.tsx
src/components-v2/common/dialogs/RewardsDialog.tsx
src/components-v2/common/dialogs/VaultDeposit.tsx
src/components-v2/common/dialogs/VaultWithdraw.tsx
src/components-v2/ibbtc-vault/IbbtcVaultDepositDialog.tsx
src/components-v2/landing/VaultItemApr.tsx
src/components-v2/vault-detail/specs/Fees.tsx
src/tests/__snapshots__/Landing.test.tsx.snap
src/tests/__snapshots__/RewardsDialog.test.tsx.snap
src/tests/__snapshots__/SettDeposit.test.tsx.snap
src/tests/__snapshots__/SettWithdraw.test.tsx.snap
src/tests/vaults/__snapshots__/VaultFiltersDialog.test.tsx.snap
src/tests/vaults/__snapshots__/VaultItemApr.test.tsx.snap
src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap
src/tests/vaults/__snapshots__/VaultsSearchControl.test.tsx.snap

- fix overflow in percentages selector
- increase max-width of dialogs
- show apr dialog when the whole container is clicked instead of just the icon

styles: UI tweaks

---

src/components-v2/ibbtc-vault/BalanceInput.tsx

feat(ibbtc-deposit): add percetnage button ripple

---

.github/workflows/codeql_analysis.yml
src/components-v2/BveCvxSpecs/index.tsx
src/components-v2/VaultDepositedAssets/index.tsx
src/config/networks-locked-deposits.ts
src/mobx/model/locked-deposits/locked-contract-info.ts
src/mobx/model/tokens/token-balance.ts
src/mobx/stores/LockedDepositsStore.ts
src/mobx/utils/helpers.ts

fix: update vault available

---

src/config/system/strategies.ts

Added user guides for all new Aura vaults

feat: added Aura user guides

---

package.json
src/components-v2/vault-detail/NewVaultWarning.tsx
src/components-v2/vault-detail/specs/VaultDetailLinks.tsx
src/config/system/strategies.ts
yarn.lock

- adds direct link to badger ninja for all vaults

chore: add ninja analytics links

---

src/components-v2/VaultApyInformation/index.tsx

Issue 2183 projected yields - showing breakdown of harvestTokens

---

src/components-v2/VaultApyInformation/index.tsx
src/hooks/useVaultInformation.ts
src/utils/componentHelpers.ts

|<img width="541" alt="Screenshot 2022-07-20 at 7 46 11 AM" src="https://user-images.githubusercontent.com/4344538/179881523-d865035c-4723-4f86-834b-a3366bbb4d6b.png">|<img width="537" alt="Screenshot 2022-07-20 at 7 46 24 AM" src="https://user-images.githubusercontent.com/4344538/179881571-c6a9c32c-8ed6-43aa-82bd-fbae83b53b14.png">|
|---|---|

Issue 2183 projected yields : Showing breakup under projected value

---

src/components-v2/landing/VaultListHeader.tsx
src/components-v2/landing/VaultListItem.tsx

Issue 2183 projected yields : Alignment fix

---

src/components-v2/common/dialogs/VaultWithdraw.tsx

use balance display format for withdrawing amount toast

chore(vault-withdraw): withdraw toast message

---

package.json
src/components-v2/InfluenceVault/InfluenceVaultInfoPanel.tsx
src/components-v2/vault-detail/charts/BoostChart.tsx
src/components-v2/vault-detail/charts/ChartTimeframeControls.tsx
src/components-v2/vault-detail/charts/ChartsCard.tsx
src/components-v2/vault-detail/charts/ChartsHeader.tsx
src/components-v2/vault-detail/charts/VaultChart.tsx
src/mobx/model/vaults/vault-charts.ts
src/mobx/stores/InfluenceVaultStore.ts
src/mobx/stores/VaultChartsStore.ts
yarn.lock

- utilize v3 api charting endpoint

feat: utilize v3 charting library

---

src/components-v2/VaultListItemTags/index.tsx
src/components-v2/common/dialogs/VaultDeposit.tsx
src/components-v2/common/dialogs/VaultDialogTitle.tsx
src/components-v2/common/dialogs/VaultWithdraw.tsx
src/components-v2/landing/VaultListItemMobile.tsx

- utilize vault type for reference

fix: reference vault type for boost

---

src/components-v2/navbar/NavbarStats.tsx
src/mobx/stores/UserStore.ts
src/tests/__snapshots__/Navbar.test.tsx.snap

Display "My APR" in the topbar next to "My Assets"

---

src/components-v2/common/dialogs/VaultDeposit.tsx
src/components-v2/ibbtc-vault/IbbtcVaultDepositDialog.tsx
src/components/Boost/Optimizer.tsx

Close Deposit/Withdraw modal on successful transaction

---

src/components-v2/common/dialogs/VaultDeposit.tsx

Displaying deposit token in deposit modal

---

src/components-v2/common/dialogs/VaultWithdraw.tsx

fix: Update withdraw value to use PPFS

---

src/config/environment.ts

fix: utilize stagin

---

src/components-v2/navbar/NavbarStats.tsx
src/tests/__snapshots__/Navbar.test.tsx.snap

|Before|After|
|---|---|
|<img width="248" alt="Screenshot 2022-08-24 at 7 23 30 PM" src="https://user-images.githubusercontent.com/4344538/186436582-b186fa93-4584-46f3-85c2-1c153d53275c.png">|<img width="225" alt="Screenshot 2022-08-24 at 10 08 35 PM" src="https://user-images.githubusercontent.com/4344538/186474525-47306c6a-ebaf-49b9-8dfc-920c5d3998f1.png">|

fix: my apr css changes

---

src/config/environment.ts

Reverts Badger-Finance/v2-ui#2316

Revert "fix: utilize stagin"

---

src/components-v2/vault-detail/charts/VaultChart.tsx

On Staging
|before|after|
|--|--|
|<img width="814" alt="Screenshot 2022-08-28 at 4 23 58 PM" src="https://user-images.githubusercontent.com/4344538/187070488-37d11179-2c24-440d-909f-16bc43e1c931.png">|<img width="818" alt="Screenshot 2022-08-28 at 4 24 20 PM" src="https://user-images.githubusercontent.com/4344538/187070493-913a124e-a53f-4aa1-a3b3-5f8bb54c8bda.png">|

fix: not using yieldApr for influence vault

---

src/components-v2/VaultSearchControls/VaultsSearchControls.tsx

Hide APY/APR toggle for yield bearing rewards

---

package.json
src/components-v2/VaultApyInformation/index.tsx
src/components-v2/vault-detail/charts/VaultChart.tsx
src/tests/__snapshots__/Landing.test.tsx.snap
src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap
yarn.lock

- align balance axis to 0, avoid misleading charts

fix: update vault yaxis

---

src/components-v2/InfluenceVault/InfluenceVaultPerfomanceTab.tsx
src/components-v2/InfluenceVault/InfluenceVaultSpecs.tsx
src/components-v2/VaultApyInformation/index.tsx
src/components-v2/YieldBearingVaults/YieldBearingVaultUtil.tsx
src/components-v2/common/VaultFees.tsx
src/components-v2/common/dialogs/VaultDeposit.tsx
src/components-v2/landing/NoVaults.tsx
src/components-v2/landing/VaultItemApr.tsx
src/components-v2/landing/VaultItemRoiTooltip.tsx
src/components-v2/vault-detail/charts/BoostChart.tsx
src/components-v2/vault-detail/specs/Fees.tsx
src/hooks/useVaultInformation.ts
src/mobx/stores/UserStore.ts
src/mobx/stores/VaultStore.ts
src/tests/__snapshots__/Landing.test.tsx.snap
src/tests/vaults/__snapshots__/VaultItemApr.test.tsx.snap
src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap
src/utils/componentHelpers.ts

Fixes No vaults provider name,
Fixes disclaimer fee text on influence/regular vault details + modal
Fixes Cap issue for BAL && Aura
Changes net to Gross yields
Historic APY -> 14day historic APY

fix: APY evolution, small text changes + Net -> gross yields

---

src/components-v2/navbar/NavbarSocialContact.tsx
src/components-v2/sidebar/index.tsx

Fix discord

---

src/components-v2/VaultApyBreakdownItem/index.tsx
src/components-v2/VaultApyInformation/index.tsx
src/mobx/utils/helpers.ts

at least make the app not crash. need to investigate what is going on with the data piplien to aurabal

fix: toFixed() crashed apy modal, handle undefined

---

public/_headers

need to double check this is all we need, messaged them waiting for response

chore: add headers

---

src/components-v2/InfluenceVault/InfluenceVaultApyBreakdown.tsx
src/components-v2/VaultApyBreakdownItem/index.tsx
src/components-v2/VaultApyInformation/index.tsx
src/components-v2/common/MissingValueSkeleton.tsx

added missing value skeleton

---

src/components-v2/VaultApyInformation/index.tsx
src/components-v2/landing/VaultItemApr.tsx
src/components-v2/vault-detail/specs/VaultMetrics.tsx
src/tests/sett-details/__snapshots__/SpecsCard.test.tsx.snap
src/tests/vaults/__snapshots__/VaultMetrics.test.tsx.snap

feat: add apy + modal to vault detail page

---

src/components-v2/navbar/NavbarTabs.tsx
src/tests/__snapshots__/Navbar.test.tsx.snap

[ISSUE-2402] | Refresh on tab doesn't show correct tab on UI

---

public/index.html
src/assets/css/body.css
src/components-v2/common/NotFound.tsx
src/components-v2/navbar/NavbarTabs.tsx
src/components-v2/vault-detail/VaultDetailWrapper.tsx
src/components/Boost/index.tsx
src/components/IbBTC/index.tsx
src/config/routes.tsx
src/config/ui/dark.tsx
src/config/ui/light.ts

|Previous|After|
|---|---|
|<img width="346" alt="Screenshot 2022-10-03 at 9 08 02 PM" src="https://user-images.githubusercontent.com/4344538/193637244-841ba4bf-7dfc-4cc9-847b-5aee9a4d973d.png">|<img width="407" alt="Screenshot 2022-10-03 at 9 08 09 PM" src="https://user-images.githubusercontent.com/4344538/193637312-3c5eb1e1-2783-4166-8aa9-3fefdd5ac62e.png">|
|previous on https://beta.badger.com/ home page||
|<img width="885" alt="Screenshot 2022-10-03 at 10 44 44 PM" src="https://user-images.githubusercontent.com/4344538/193638491-878cd212-a8dd-4cf3-91eb-5a83ecc4e185.png">||

Route based code split

---

src/components-v2/common/NetworkGasWidget.tsx
src/components-v2/landing/NoVaults.tsx
src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap

Fixed the issue with the `Switch Networks` button not opening the network dropdown.
|||
|--|--|
|<img width="1147" alt="Screenshot 2022-10-11 at 8 52 11 PM" src="https://user-images.githubusercontent.com/4344538/195405847-eceaeb26-47d1-4b7d-b3c7-499b711f285a.png">|<img width="1169" alt="Screenshot 2022-10-11 at 8 43 08 PM" src="https://user-images.githubusercontent.com/4344538/195405861-2a8d812d-c2ae-4317-9641-5cbcf2a91e2e.png">|

[ISSUE-2333] Added notice for Polygon and BSC network wind down

---

package.json
src/config/constants.ts
src/config/enums/wallets.enum.ts
src/config/wallets.ts
src/tests/WalletWidget.test.tsx
yarn.lock

|Before|After|
|---|---|
|<img width="407" alt="Screenshot 2022-10-03 at 9 08 09 PM" src="https://user-images.githubusercontent.com/4344538/195108130-0c8b55b6-da6b-48e0-a845-10948180ac71.png">|<img width="372" alt="Screenshot 2022-10-11 at 7 14 44 PM" src="https://user-images.githubusercontent.com/4344538/195108099-484f74b8-9620-4892-bf2c-bd6f20e501c2.png">|

Removed Coinbase and Portis wallet

---

package.json
yarn.lock

- upgrade sdk version for ibbtc fix

fix: utilize new sdk version

---

src/mobx/stores/RootStore.ts

fix: lint code

---

src/components/IbBTC/Mint.tsx
src/components/IbBTC/Redeem.tsx

[ISSUE-2425] | Showing asset dropdown before wallet connect.

---

src/components-v2/vault-detail/holdings/DepositInfo.tsx
src/components-v2/vault-detail/holdings/NoHoldings.tsx
src/components-v2/vault-detail/specs/VaultDetailLinks.tsx
src/tests/sett-details/__snapshots__/SpecsCard.test.tsx.snap

| Before | After |
|---|---|
|![screencapture-beta-badger-vault-curve-renbtc-wbtc-2022-11-02-22_56_04- before](https://user-images.githubusercontent.com/4344538/199561512-c08ea9a3-5024-41e5-9d0c-40219070d5bb.png)|![screencapture-localhost-3000-vault-curve-renbtc-wbtc-2022-11-02-22_56_13](https://user-images.githubusercontent.com/4344538/199561530-06549c13-d8a0-4f95-8eae-df877842f0bb.png)|

[ISSUE-2437] Remove user guide for deprecated vault

---

package.json
src/components-v2/landing/VaultBehaviorTooltip.tsx
yarn.lock

Updated sdk version to 1.19.1 to remove Helper filter

---

src/config/constants.ts
src/config/system/strategies.ts
src/tests/sett-details/__snapshots__/SpecsCard.test.tsx.snap

renBTC announcment

---

package.json

Fixed failing test cases when raising PR from development -> staging and staging -> master.

Issue 2508 test fails on development -> staging
